Repository hubverse-org/hubDocs, pull requests merged in 2025-05, with the labels that each got.

#313 Add page for dashboard tools
  docs/source/developer/dashboard-tools.md
  docs/source/index.md
Labels: documentation

#325 small fixes and edits
  docs/source/developer/index.md
  docs/source/index.md
  docs/source/overview/contributors.md
  docs/source/overview/support-consulting.md
  docs/source/user-guide/target-data.md
Labels: documentation

#338 fix hyperlink
  docs/source/overview/history.md
Labels: documentation

#337 Fixing multiple targets (doc and ref) for #dashboard-predevals
  docs/source/developer/dashboard-site.md
  docs/source/user-guide/dashboards.md
Labels: bug

#341 Deleting history from hubDocs and linting
  docs/source/index.md
  docs/source/overview/history.md
Labels: documentation

#342 add tip for downloading data from remote sources
  docs/source/developer/dashboard-local.md
Labels: documentation

#340 it started with a typo
  docs/source/user-guide/target-data.md
Labels: documentation

#336 instructions for dashboard staging
  docs/source/developer/dashboard-staging.md
  docs/source/index.md
Labels: documentation, higher priority

#339 add escape routes for users who are trapped and afraid by the dashboard workflows
  docs/source/user-guide/dashboards.md
Labels: documentation, higher priority
